import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { unzipSync } from "fflate";
import { fixtureConfig } from "../fixtures";

test("exports unsaved draft with avatar/card images and restores them into another profile", async ({ page, request }) => {
  const base = "http://127.0.0.1:3001";
  const image = Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" fill="#a78bfa"/></svg>');
  const uploaded = await request.post(`${base}/api/assets`, { multipart: { file: { name: "icon.svg", mimeType: "image/svg+xml", buffer: image } } });
  expect(uploaded.ok()).toBe(true);
  const { id: assetId } = await uploaded.json();
  const { profile: source } = await (await request.post(`${base}/api/profiles`, { data: { name: "Bundle source" } })).json();
  const { profile: target } = await (await request.post(`${base}/api/profiles`, { data: { name: "Bundle target" } })).json();
  const config = fixtureConfig();
  config.homepage.title = "Bundle source";
  config.homepage.icon = { type: "asset", assetId };
  config.tabs[0].sections[0].cards[0].icon = { type: "asset", assetId };
  await request.put(`${base}/api/profiles/${source.id}/config`, { data: config });
  await page.addInitScript((id: string) => { if (!localStorage.getItem("chroma.active-profile")) localStorage.setItem("chroma.active-profile", id); }, source.id);
  await page.goto("/");
  await page.getByTestId("profile-switcher").click();
  await page.getByRole("menuitem", { name: "Homepage settings", exact: true }).click();
  await page.getByLabel("Homepage title / profile name", { exact: true }).fill("Portable draft");
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export configuration", exact: true }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe("Portable-draft.zip");
  const zip = await readFile((await download.path())!);
  const files = unzipSync(zip);
  expect(Object.keys(files).sort()).toEqual([`assets/${assetId}.svg`, "config.json", "manifest.json"]);
  expect(Buffer.from(files[`assets/${assetId}.svg`])).toEqual(image);
  expect(JSON.parse(Buffer.from(files["config.json"]).toString()).homepage.title).toBe("Portable draft");
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await page.evaluate((id: string) => localStorage.setItem("chroma.active-profile", id), target.id);
  await page.reload();
  await expect(page.getByRole("heading", { name: "Bundle target", exact: true })).toBeVisible();
  await page.getByTestId("profile-switcher").click();
  await page.getByRole("menuitem", { name: "Homepage settings", exact: true }).click();
  await page.getByLabel("Dashboard ZIP or JSON file", { exact: true }).setInputFiles({ name: "Portable-draft.zip", mimeType: "application/zip", buffer: zip });
  await expect(page.getByRole("heading", { name: "Portable draft", exact: true })).toBeVisible();
  await expect(page.getByTestId("card-card-a")).toBeVisible();
  const cardImage = page.getByTestId("card-card-a").locator("img");
  await expect.poll(() => cardImage.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true);
  expect((await (await request.get(`${base}/api/profiles/${target.id}/config`)).json()).homepage.title).toBe("Bundle target");
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Bundle target", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Redo", exact: true }).click();
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save", exact: true })).toBeHidden();
  const restored = await (await request.get(`${base}/api/profiles/${target.id}/config`)).json();
  expect(restored.homepage.icon.assetId).not.toBe(assetId);
  expect(restored.tabs[0].sections[0].cards[0].icon.assetId).toBe(restored.homepage.icon.assetId);
  expect(await (await request.get(`${base}/api/assets/${restored.homepage.icon.assetId}`)).body()).toEqual(image);
  expect((await (await request.get(`${base}/api/profiles/${source.id}/config`)).json()).homepage.title).toBe("Bundle source");
  await page.reload();
  await expect.poll(() => page.getByTestId("card-card-a").locator("img").evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true);
});
