import { expect, test } from "@playwright/test";
import { fixtureConfig } from "../fixtures";
import { remoteHouseExample } from "../../src/shared/remote-card";

test("adds a custom card, tests the real mock endpoint, saves a credential securely and persists settings", async ({ page, request }) => {
  const { profile } = await (await request.post("http://127.0.0.1:3001/api/profiles", { data: { name: "Custom sandbox" } })).json();
  const configEndpoint = `http://127.0.0.1:3001/api/profiles/${profile.id}/config`;
  await request.put(configEndpoint, { data: fixtureConfig() });
  await page.addInitScript((id) => localStorage.setItem("chroma.active-profile", id), profile.id);
  await page.goto("/");
  await page.getByTestId("profile-switcher").click();
  await page.getByRole("menuitem", { name: "Homepage settings", exact: true }).click();
  await page.getByRole("button", { name: "Add new item", exact: true }).click();
  await page.getByTestId("add-remote-card").click();
  const card = page.getByTestId("remote-card-content");
  await expect(card.getByText("Demo · Home secure")).toBeVisible();
  await expect(card.getByText("22.4 °C")).toBeVisible();
  await expect(card.getByRole("progressbar", { name: "Home battery" })).toHaveAttribute("aria-valuenow", "76");
  await expect(card.getByRole("link", { name: "Open Home Assistant" })).toBeHidden();
  await page.getByRole("textbox", { name: "JSON endpoint" }).fill("http://127.0.0.1:3001/api/examples/house");
  await page.getByRole("checkbox", { name: "Allow local network" }).check();
  await page.getByRole("button", { name: "Test endpoint" }).click();
  const inspector = page.locator("aside");
  await expect(inspector.getByText(/Valid chroma-card\/v1/)).toBeVisible();
  await expect(inspector.getByText("Response preview", { exact: true })).toBeVisible();
  await page.getByRole("combobox", { name: "Endpoint authentication" }).selectOption("bearer");
  const secret = "test-only-browser-placeholder";
  await page.getByLabel("Endpoint secret", { exact: true }).fill(secret);
  await page.getByRole("button", { name: "Save credential", exact: true }).click();
  await expect(page.getByText("Credential configured (encrypted)")).toBeVisible();
  await expect(page.getByLabel("Endpoint secret", { exact: true })).toHaveValue("");
  await page.getByRole("button", { name: "Test endpoint" }).click();
  await expect(inspector.getByText(/Valid chroma-card\/v1/)).toBeVisible();
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save", exact: true })).toBeHidden();
  await expect(card.getByRole("link", { name: "Open Home Assistant" })).toHaveAttribute("href", "http://homeassistant.local:8123/");
  const saved = await (await request.get(configEndpoint)).json();
  const custom = saved.tabs[0].sections[0].cards.at(-1);
  expect(custom).toMatchObject({ type: "remote-data", endpoint: "http://127.0.0.1:3001/api/examples/house", authMode: "bearer", allowLocalNetwork: true });
  expect(custom.credentialId).toBeTruthy(); expect(JSON.stringify(saved)).not.toContain(secret);
  await page.reload();
  await expect(card.getByText("Locked", { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
});

test("renders remote text inertly and keeps data visibly stale after failures", async ({ page, request }) => {
  const { profile } = await (await request.post("http://127.0.0.1:3001/api/profiles", { data: { name: "Custom stale sandbox" } })).json();
  const config = fixtureConfig();
  config.tabs[0].sections[0].cards.push({ id: "remote-fixture", type: "remote-data", label: "House", icon: { type: "iconify", value: "lucide:house" }, endpoint: "https://example.com/card", authMode: "none", allowLocalNetwork: false, refreshSeconds: 30 });
  await request.put(`http://127.0.0.1:3001/api/profiles/${profile.id}/config`, { data: config });
  await page.addInitScript((id) => localStorage.setItem("chroma.active-profile", id), profile.id);
  const data = remoteHouseExample(); data.blocks[0] = { type: "text", text: '<img src=x onerror="window.remoteExecuted=true">' };
  await page.route("**/api/widgets/remote-data", (route) => route.fulfill({ json: { data, fetchedAt: "2026-09-28T08:00:00.000Z", stale: true, cache: "stale", nextRefreshSeconds: 60, error: "Endpoint temporarily unavailable" } }));
  await page.goto("/");
  const card = page.getByTestId("remote-card-content");
  await expect(card.getByText(/Stale — showing last valid data/)).toBeVisible();
  await expect(card.getByText('<img src=x onerror="window.remoteExecuted=true">', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => "remoteExecuted" in window)).toBe(false);
  expect(await card.locator('img[src="x"]').count()).toBe(0);
});

test("retains the last response after a failed poll and clears it when changing source", async ({ page, request }) => {
  const { profile } = await (await request.post("http://127.0.0.1:3001/api/profiles", { data: { name: "Custom polling sandbox" } })).json();
  const config = fixtureConfig();
  config.tabs[0].sections[0].cards.push({ id: "poll-fixture", type: "remote-data", label: "House", icon: { type: "iconify", value: "lucide:house" }, endpoint: "https://example.com/card", authMode: "none", allowLocalNetwork: false, refreshSeconds: 30 });
  await request.put(`http://127.0.0.1:3001/api/profiles/${profile.id}/config`, { data: config });
  await page.addInitScript((id) => localStorage.setItem("chroma.active-profile", id), profile.id);
  let failed = false;
  await page.route("**/api/widgets/remote-data", (route) => {
    if (route.request().postDataJSON().endpoint.endsWith("/other")) return route.fulfill({ json: { data: { protocol: "chroma-card/v1", blocks: [{ type: "text", text: "Different source" }], actions: [] }, fetchedAt: "2026-09-28T08:05:00.000Z", stale: false, cache: "fresh", nextRefreshSeconds: 30 } });
    return failed ? route.fulfill({ status: 503, json: { error: "Test endpoint offline" } }) : route.fulfill({ json: { data: remoteHouseExample(), fetchedAt: "2026-09-28T08:00:00.000Z", stale: false, cache: "fresh", nextRefreshSeconds: 30 } });
  });
  await page.clock.install();
  await page.goto("/");
  const card = page.getByTestId("remote-card-content");
  await expect(card.getByText("Loading custom card…")).toBeVisible();
  await page.clock.runFor(500);
  await expect(card.getByText("Locked", { exact: true })).toBeVisible();
  failed = true;
  await page.clock.fastForward(31000);
  await expect(card.getByText(/Stale — showing last valid data/)).toBeVisible();
  await expect(card.getByText("Locked", { exact: true })).toBeVisible();
  await page.getByTestId("profile-switcher").click();
  await page.getByRole("menuitem", { name: "Homepage settings", exact: true }).click();
  await page.getByTestId("card-poll-fixture").click();
  await page.getByRole("textbox", { name: "JSON endpoint" }).fill("https://example.com/other");
  await expect(card.getByText("Locked", { exact: true })).toBeHidden();
  await page.clock.runFor(500);
  await expect(card.getByText("Different source", { exact: true })).toBeVisible();
  await expect(card.getByText(/Test endpoint offline/)).toBeHidden();
});
